// <auto-generated />
using System;
using DengeWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DengeWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824091339_AddAdminUsers")]
    partial class AddAdminUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DengeWeb.Models.AdminUser", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").HasMaxLength(320).IsRequired().HasColumnType("nvarchar(320)");
                    b.Property<int>("FailedAttempts").HasColumnType("int");
                    b.Property<DateTime?>("LockoutEnd").HasColumnType("datetime2");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ResetToken").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ResetTokenExpiry").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("DengeWeb.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("DengeWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrochureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("GalleryUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DengeWeb.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutEthicalValuesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutEthicalValuesTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutMissionVisionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutMissionVisionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutMissionVisionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValuesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValuesImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValuesTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterCopyrightText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterFacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterInstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLinkedinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterTwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterYoutubeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMapEmbedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderWhiteLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexAboutButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexAboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexAboutImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexAboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexContactButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexContactDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexContactSubtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexEntryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexEntryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexStockVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
